name: 'Check stale community issues.'
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  stale-year-old:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@65d24b70926a596b0f0098d7e1eb572175d73bc1
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-issue-message: 'This issue is stale because it has been 365 days with no activity. Please provide an update via a comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 365 days with no activity.'
          days-before-stale: 365
          days-before-close: 5
          days-before-pr-close: -1
          days-before-pr-stale: -1
          stale-issue-label: closing-soon
          stale-pr-label: DONTUSE
          only-issue-labels: community
          labels-to-remove-when-unstale: closing-soon
          exempt-issue-labels: review,implementation,ready-for-review,response-requested
