name: 'Close stale community PRs in review stage.'
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-pr-message: 'This PR is stale because it has been 15 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-pr-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 15
          days-before-close: 5
          days-before-issue-close: -1
          days-before-issue-stale: -1
          only-pr-labels: community,review,response-requested
