name: 'Close stale community PRs in implementation stage.'
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-pr-message: 'This PR is stale because it has been 20 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-pr-message: 'This issue was closed because it has been stalled for 10 days with no activity.'
          days-before-stale: 20
          days-before-close: 10
          days-before-issue-close: -1
          days-before-issue-stale: -1
          only-issue-labels: community,response-requested
