name: 'Check stale community PRs.'
on:
  pull_request:
    types:
      - workflow_dispatch
      
jobs:
  stale-implementation-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@65d24b70926a596b0f0098d7e1eb572175d73bc1
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-pr-label: stale
          stale-pr-message: 'This PR is stale because it has been 0 days with no activity. Remove stale label or comment or this will be closed in 1 days.'
          close-pr-message: 'This issue was closed because it has been stalled for 1 days with no activity.'
          days-before-stale: 0
          days-before-close: 1
          days-before-issue-close: -1
          days-before-issue-stale: -1
          only-pr-labels: community,implementation,response-requested
          labels-to-remove-when-unstale: stale,response-requested
  stale-review-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@65d24b70926a596b0f0098d7e1eb572175d73bc1
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-pr-label: stale
          stale-pr-message: 'This PR is stale because it has been 0 days with no activity. Remove stale label or comment or this will be closed in 1 days.'
          close-pr-message: 'This issue was closed because it has been stalled for 1 days with no activity.'
          days-before-stale: 0
          days-before-close: 1
          days-before-issue-close: -1
          days-before-issue-stale: -1
          only-pr-labels: community,review,response-requested
          labels-to-remove-when-unstale: stale,response-requested

