name: 'Check stale community PRs.'
on: workflow_dispatch
      
jobs:
  stale-implementation-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@65d24b70926a596b0f0098d7e1eb572175d73bc1
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-pr-label: stale
          stale-pr-message: 'This pull request is in the implementation stage. It has become stale because it has been 20 days with no activity. Please comment with an update or this will be closed in 10 days.'
          close-pr-message: 'This pull request was closed because it has been stalled for 10 days with no activity.'
          days-before-stale: 20
          days-before-close: 10
          days-before-issue-close: -1
          days-before-issue-stale: -1
          only-pr-labels: community,implementation,response-requested
          labels-to-remove-when-unstale: response-requested
  stale-review-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@65d24b70926a596b0f0098d7e1eb572175d73bc1
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          stale-pr-label: stale
          stale-pr-message: 'This pull request is in the review stage. It has become stale because it has been 15 days with no activity. Please comment with an update to indicate work is still ongoing.'
          close-pr-message: 'This pull request was closed because it has been stale for 5 days with no activity.'
          days-before-stale: 15
          days-before-close: 5
          days-before-issue-close: -1
          days-before-issue-stale: -1
          only-pr-labels: community,review,response-requested
          labels-to-remove-when-unstale: response-requested

